/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ocp.countdowntimer;

import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class Frame extends javax.swing.JFrame {

    private ScheduledExecutorService service = Executors.newSingleThreadScheduledExecutor();
    private CountDownThread Cdt;
    private CaculatorGoal caculatorGoal = new CaculatorGoal();
    private Util util = new Util();
    private long startTime;
    private String resultShow;

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        resultArea.setText("剩餘時間  00 ： 00");
    }

    public void resultShowOnArea() {
        util.changeTimeType(caculatorGoal.getGoalnumbers());
        int minutesShow = util.getMinutes();
        int secondsShow = util.getSeconds();
        String show = String.format("剩餘時間  %02d ： %02d", minutesShow, secondsShow);
        resultArea.setText(show);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        minute1 = new javax.swing.JButton();
        minute3 = new javax.swing.JButton();
        minute2 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Start = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        minute1.setText("1分鐘");
        minute1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minute1ActionPerformed(evt);
            }
        });

        minute3.setText("3分鐘");
        minute3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minute3ActionPerformed(evt);
            }
        });

        minute2.setText("2分鐘");
        minute2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minute2ActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        resultArea.setColumns(20);
        resultArea.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        resultArea.setRows(5);
        resultArea.setAlignmentX(1.0F);
        resultArea.setAlignmentY(1.0F);
        jScrollPane2.setViewportView(resultArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(minute1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(minute2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(minute3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minute1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minute3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minute2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void minute2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minute2ActionPerformed
        // TODO add your handling code here:
        if (caculatorGoal.ifRun != true) {
            caculatorGoal.buttonSetGoalnumbers(120);
            resultShowOnArea();

        }
    }//GEN-LAST:event_minute2ActionPerformed

    private void minute3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minute3ActionPerformed
        // TODO add your handling code here:
        if (caculatorGoal.ifRun != true) {
            caculatorGoal.buttonSetGoalnumbers(180);
            resultShowOnArea();

        }
    }//GEN-LAST:event_minute3ActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        long startTime = System.currentTimeMillis();
        if (!caculatorGoal.ifRun) {
            util.changeTimeType(caculatorGoal.getGoalnumbers());//把要倒數的總秒數轉換成分鐘跟秒鐘
            caculatorGoal.ifRun = true;
            long startTimeInBlock = startTime;
            CountDownThread Cdt = new CountDownThread(startTimeInBlock, util, caculatorGoal, resultArea, service);
            int initDelay = 0;
            int delay = 1;
            service.scheduleAtFixedRate(Cdt, initDelay, delay, TimeUnit.SECONDS);
        }

//為什麼不能這樣處理
//        while (true) {
//            System.out.println("test");
//            if ((Cdt.getCheckNumber() == 0) || forceToClose) {
//                service.shutdown();
//                return;
//            }
//       }
// sdfefg
    }//GEN-LAST:event_StartActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        service.shutdown();
        caculatorGoal.ifRun = false;
        caculatorGoal.setGoalnumbers(0);
        service = Executors.newSingleThreadScheduledExecutor();
        resultArea.setText("剩餘時間  00 ： 00\n請重新設定！");
    }//GEN-LAST:event_ResetActionPerformed

    private void minute1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minute1ActionPerformed
        // TODO add your handling code here:
        if (caculatorGoal.ifRun != true) {
            caculatorGoal.buttonSetGoalnumbers(60);
            resultShowOnArea();
        }
    }//GEN-LAST:event_minute1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton Start;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton minute1;
    private javax.swing.JButton minute2;
    private javax.swing.JButton minute3;
    private javax.swing.JTextArea resultArea;
    // End of variables declaration//GEN-END:variables
}
